-- market_events — SERVICES-OWNED table. NOT managed by drizzle-kit.
--
-- DDL authority lives in nodalpulse-services/sql/add_market_events.sql.
-- This file was used to apply the initial DDL on 2026-06-03 via apply-sql.mjs
-- because it was the only available raw-SQL apply path at the time.
-- Future schema changes go through services/sql/, NOT drizzle-kit migrate.
--
-- DO NOT add this table to nodalpulse-web/db/schema/index.ts — that would
-- incorrectly transfer ownership to drizzle and risk snapshot drift (#52).
-- The table is read-only from web context.
